### ISSUE TITLE
也许应该去除.idea以及避免直接在项目中包含jar包

### ISSUE THREAD

**Issue by tang-hi** [Smileslime47/LeetCodeInputHelper#2]
我们也许应该在.gitignore中添加.idea以及jar包。
README是否应该按照惯例改为README.md?

**Comment by wuhunyu** [comment]
你这么说，应该再添加 .gitignore 忽略文件的

**Comment by Smileslime47** [comment]
去掉了jar包！顺便增加了完整样例输入的解析支持
