### ISSUE TITLE
README中的example使用text block是否更好？

### ISSUE THREAD

**Issue by tang-hi** [Smileslime47/LeetCodeInputHelper#3]
现在README中的实例通过转义字符来显示
````java
@LeetCodeData("[\"tars\",\"rats\",\"arts\",\"star\"]")
````

如果使用text block是否可读性更好，因为我注意到这个项目使用的是jdk19。

````java
@LeetCodeData(value = """
        ["tars","rats","arts","star"]""")
````

**Comment by Smileslime47** [comment]
不是这样的，Java中字符串里不能直接输入双引号"，否则会被解析，所以要在字符串里的每个双引号前加上转义字符。
不过这个并不会造成问题，因为你从外界复制字符串到IDE上的时候，IDE会自动加上转义字符

**Comment by tang-hi** [comment]
> 抱歉我之前理解错了，你说的对，这两种写法都是正确的

使用textblock的缺点是一定要有换行，数据会在第二行，这看上去并不是很美观，当然这两种方案我觉得都可以，你可以按照自己的审美决定哪个写法更好

**Comment by Smileslime47** [comment]
这两种我试了都可以正常解析，都写上来让大家自己选吧（
